#! /usr/bin/env python
#
import os, sys
from xjs.trans.cli import JSONT

prog = os.path.basename(sys.argv[0])
if not prog or prog == 'python':
    prog = "JSONT"

runner = JSONT(prog)

sys.exit(runner.execute())
