#! /bin/bash
#
prog=`basename $0`

JQ_ARGS=()
params=

while [ ${#@} -gt 0 ]; do
    case "$1" in
        "--config")
            params="$params $2 $3"
            shift 2
            ;;
        *)
            JQ_ARGS+=("$1")
            ;;
    esac
    shift
done

function build_config {

    echo -n "{}"

    while [ ${#@} -gt 0 ]; do
        echo -n " | .$1 = $2" 
        shift 2
    done
    echo ""
}

cfgin=`build_config $params`
cfg=`jq -nc "$cfgin"`

jq --argjson config "$cfg" "${JQ_ARGS[@]}"





    
